return {
	["HTTP 400 (Game)"] = "Error 401 — Publish the game first.",
	["HTTP 403"] = "Error 403 — Access forbidden.",
	["HTTP 404"] = "Error 404 — Resource not found.",
	["HTTP 409 (Conflict)"] = "Error 409 — Outdated or cmd not running.",
	["HTTP 429"] = "Error 429 — Rate limited. Slow down.",
	["HTTP 500 (Internal Server Error)"] = "Error 500 — Internal server error.",
	["HTTP 503 (Service Unavailable)"] = "Error 503 — Server unavailable.",
}
